#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Booking Management System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Check if node_modules exists (symlink to parent)
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Warning: node_modules not found. This project uses symlinked node_modules from parent.${NC}"
    echo "If you encounter issues, run this from the parent project directory."
fi

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

# Check if npm is available
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

# Check if .env.local exists
if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found. Creating from template...${NC}"
    cat > .env.local << EOF
# Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicG5wX2VyIiwicG9zIjoiYXV0byIsInVsIjoiaXN5eXAiOiJyZW0iLCJ0eXBlIjoiY2FsbCIsIm5hbWUiOiJwdWJsaWMifQ==
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwicG9zIjoiYXV0byIsInVsIjoiaXN5eXAiOiJyZW0iLCJ0eXBlIjoiY2FsbCIsIm5hbWUiOiJzZXJ2aWNlIn0=
EOF
    echo -e "${GREEN}.env.local created${NC}"
fi

# ============================================
# START NEXT.JS DEV SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."

# Start Next.js in background
npm run dev &
NEXT_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUPABASE STATUS CHECK
# ============================================

echo ""
echo "Checking Supabase status..."

# Check if Supabase is running
if nc -z localhost 54321 2>/dev/null; then
    echo -e "${GREEN}Supabase is running${NC}"
else
    echo -e "${YELLOW}Supabase does not appear to be running on port 54321${NC}"
    echo "To start Supabase locally, run: supabase start"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:     http://localhost:3000"
echo ""
echo "Booking Management Page:"
echo "  http://localhost:3000/dashboard-business-jobs"
echo ""
echo "To stop the server, run: kill $NEXT_PID"
echo "Or press Ctrl+C if running in foreground"
echo ""

# Keep script running if started interactively
if [ -t 0 ]; then
    echo "Press Ctrl+C to stop the server..."
    trap "echo 'Stopping Next.js...'; kill $NEXT_PID; exit 0" INT TERM
    wait $NEXT_PID
fi
