#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Worker Booking Dashboard

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================
echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js first.${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm first.${NC}"
    exit 1
fi

echo -e "${GREEN}Dependencies OK${NC}"

# ============================================
# INSTALL NPM DEPENDENCIES
# ============================================
echo ""
echo "Installing npm dependencies..."
if [ ! -d "node_modules" ]; then
    npm install
    echo -e "${GREEN}Dependencies installed${NC}"
else
    echo -e "${YELLOW}node_modules exists, skipping npm install${NC}"
fi

# ============================================
# CHECK ENVIRONMENT
# ============================================
echo ""
echo "Checking environment..."

if [ ! -f ".env.local" ]; then
    echo -e "${YELLOW}Warning: .env.local not found${NC}"
    echo "Please ensure NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY are set"
else
    echo -e "${GREEN}.env.local found${NC}"
fi

# ============================================
# START FRONTEND
# ============================================
echo ""
echo "========================================"
echo "Starting Frontend (Next.js)"
echo "========================================"

npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Worker Booking Dashboard will be available at:"
echo "  http://localhost:3000/dashboard/worker/bookings"
echo ""
echo "To stop the environment, press Ctrl+C"
echo ""

# Keep script running
trap "echo ''; echo 'Stopping...'; kill $FRONTEND_PID 2>/dev/null; exit 0" INT TERM

wait
