#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Job Application System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Job Application System"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi

if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi

if ! command -v supabase &> /dev/null; then
    echo -e "${YELLOW}Supabase CLI not found. Installing...${NC}"
    npm install -g supabase
fi

echo -e "${GREEN}Dependencies OK${NC}"

# ============================================
# INSTALL NPM DEPENDENCIES
# ============================================

echo ""
echo "Installing npm dependencies..."
if [ ! -d "node_modules" ]; then
    npm install
    echo -e "${GREEN}Dependencies installed${NC}"
else
    echo -e "${YELLOW}node_modules exists, skipping...${NC}"
fi

# ============================================
# CHECK SUPABASE
# ============================================

echo ""
echo "Checking Supabase..."

# Check if Supabase is running
if nc -z localhost 54321 2>/dev/null; then
    echo -e "${GREEN}Supabase is already running${NC}"
else
    echo -e "${YELLOW}Starting Supabase...${NC}"
    supabase start

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}Supabase started successfully${NC}"
    else
        echo -e "${RED}Failed to start Supabase${NC}"
        echo "Please ensure Docker is running and try again"
        exit 1
    fi
fi

# ============================================
# APPLY DATABASE MIGRATIONS
# ============================================

echo ""
echo "Applying database migrations..."
supabase db reset
echo -e "${GREEN}Database migrations applied${NC}"

# ============================================
# START NEXT.JS DEV SERVER
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &
NEXT_PID=$!

wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:       http://localhost:3000"
echo "  Supabase API:  http://localhost:54321"
echo "  Supabase Studio: http://localhost:8000"
echo ""
echo "Pages:"
echo "  Worker Dashboard: http://localhost:3000/dashboard-worker-jobs"
echo "  Business Dashboard: http://localhost:3000/dashboard-business-jobs"
echo ""
echo -e "${GREEN}Press Ctrl+C to stop all services${NC}"
echo ""

# Wait for interrupt
trap "echo ''; echo 'Stopping services...'; kill $NEXT_PID 2>/dev/null; supabase stop 2>/dev/null; echo 'Done'; exit 0" INT

# Keep script running
wait $NEXT_PID
